[package]
name = "stable_mir_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive", "cargo", "env"] }
z3 = {version="0.12", features = ["static-link-z3"]}

[package.metadata.rust-analyzer]
rustc_private = true